### ISSUE TITLE
Unable to install via npm; Could not read from remote repository.

### ISSUE THREAD

**Issue by ndugger** [cocos-creator/editor-framework#184]
I was able to fix this by setting up my local ssh key for github. This can be closed now, but **I suggest fixing this by putting the github dependencies on npm.**

---

Here's my console output when trying to run `npm install cocos-creator/editor-framework`

(Here's the latter portion of my npm-debug, starting with the first error: http://pastebin.com/kkmJY2cQ)
```
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

> fsevents@1.0.6 install /Users/personal/Desktop/vorge/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/personal/Desktop/vorge/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> editor-framework@0.4.0 install /Users/personal/Desktop/vorge/node_modules/editor-framework
> gulp bootstrap && bower install && gulp npm-rebuild

[14:36:29] Using gulpfile ~/Desktop/vorge/node_modules/editor-framework/gulpfile.js
[14:36:30] Starting 'bootstrap'...
[14:36:30] Starting 'setup-branch'...
Setup submodule branch local setting. You can change "local-setting.json" to specify your branches.
[14:36:30] Finished 'setup-branch' after 1.47 ms
[14:36:30] Starting 'update-hosts'...
git clone git@github.com:fireball-packages/package-examples.git package-examples in 
[14:36:30] Starting 'update-builtin'...
git clone git@github.com:fireball-packages/console.git builtin/console in 
git clone git@github.com:fireball-packages/ipc-debugger.git builtin/ipc-debugger in 
git clone git@github.com:fireball-packages/package-manager.git builtin/package-manager in 
git clone git@github.com:fireball-packages/tester.git builtin/tester in 
git clone git@github.com:fireball-packages/ui-kit.git builtin/ui-kit in 
Cloning into 'package-examples'...
Cloning into 'builtin/console'...
Cloning into 'builtin/ipc-debugger'...
Cloning into 'builtin/package-manager'...
Cloning into 'builtin/tester'...
Cloning into 'builtin/ui-kit'...
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[14:36:32] 'update-builtin' errored after 2.76 s
[14:36:32] Error: Failed to exec git clone git@github.com:fireball-packages/package-manager.git builtin/package-manager
    at ChildProcess.<anonymous> (/Users/personal/Desktop/vorge/node_modules/editor-framework/utils/libs/git.js:36:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[14:36:32] 'bootstrap' errored after 2.77 s
[14:36:32] Error: Failed to exec git clone git@github.com:fireball-packages/package-manager.git builtin/package-manager
    at ChildProcess.<anonymous> (/Users/personal/Desktop/vorge/node_modules/editor-framework/utils/libs/git.js:36:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[14:36:32] 'update-hosts' errored after 2.8 s
[14:36:32] Error: Failed to exec git clone git@github.com:fireball-packages/package-examples.git package-examples
    at ChildProcess.<anonymous> (/Users/personal/Desktop/vorge/node_modules/editor-framework/utils/libs/git.js:36:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
vorge@0.0.1-alpha /Users/personal/Desktop/vorge
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/personal/.nvm/versions/node/v5.5.0/bin/node" "/Users/personal/.nvm/versions/node/v5.5.0/bin/npm" "install" "cocos-creator/editor-framework" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! editor-framework@0.4.0 install: `gulp bootstrap && bower install && gulp npm-rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the editor-framework@0.4.0 install script 'gulp bootstrap && bower install && gulp npm-rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the editor-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp bootstrap && bower install && gulp npm-rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls editor-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/personal/Desktop/vorge/npm-debug.log
npm ERR! code 1
```

**Comment by jwu** [comment]
I got that. The reason I clone builtin repo in this way is because they are optional to developer. And people clone the repo may want to develop it.

To solve the problem, I will reconsider using https instead of ssh for git-clone.

**Comment by jwu** [comment]
Hi @ndugger , I'm trying to fix the issue by the commit above. Would you mind to test it again and give me the feedback?
